In [ ]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/drive/Shareddrives/CMPUT 664 : SSE/Data/adult census/adult.data',header= None,delimiter=",")
df[14] = np.where(df[14]==' <=50K', 0, 1)
df.columns = ['age','workclass','fnlwgt','education','education_num','marital_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week','native_country','<50k']
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,<50k
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

In [ ]:
# Modifying continuous atatributes : age, fnlwgt,education_num, education-num,capital-gain,capital-loss, hours-per-week
import random
age = list(df.age.values)
fnlwgt = list(df.fnlwgt.values)
education_num = list(df.education_num.values)
capital_gain = list(df.capital_gain.values)
capital_loss = list(df.capital_loss.values)
hour_per_week = list(df.hours_per_week.values)


mod_age = []
mod_fnlget = []
mod_education_num = []
mod_capital_gain = []
mod_capital_loss = []
mod_hour_per_week = []

for i in range(len(age)):
  mod_age.append(age[i]* random.uniform(0.8, 1))
  mod_fnlget.append(fnlwgt[i]*random.uniform(0.8,1))
  
  mod_education_num.append(education_num[i]* random.uniform(0.8, 1))
  mod_capital_gain.append(capital_gain[i]* random.uniform(0.8, 1))
  mod_capital_loss.append(capital_loss[i]* random.uniform(0.8, 1))
  mod_hour_per_week.append(hour_per_week[i]* random.uniform(0.8, 1))

In [ ]:
df['age'] = mod_age
df['fnlwgt'] = mod_fnlget
df['education_num'] = mod_education_num
df['capital_gain'] = mod_capital_gain
df['capital_loss'] = mod_capital_loss
df['hours_per_week'] = mod_hour_per_week

In [ ]:
df.to_csv('synthetic_data_adult_census.csv')

In [ ]:
df.head(5)

         age          workclass  ...  native_country <50k
0  38.175219          State-gov  ...   United-States    0
1  45.844758   Self-emp-not-inc  ...   United-States    0
2  34.819321            Private  ...   United-States    0
3  47.290600            Private  ...   United-States    0
4  25.939754            Private  ...            Cuba    0

[5 rows x 15 columns]

In [ ]:
x = df.drop(14,axis = 1 )
y = df[14]
x = pd.get_dummies(x)

x.head()

KeyError: ignored

# Customer Synthetic dataset

In [ ]:
!unzip '/content/drive/Shareddrives/CMPUT 664 : SSE/Data/customer_value.zip' -d '/content/drive/Shareddrives/CMPUT 664 : SSE/Data'

Archive:  /content/drive/Shareddrives/CMPUT 664 : SSE/Data/customer_value.zip
  inflating: /content/drive/Shareddrives/CMPUT 664 : SSE/Data/offers.csv.gz
  inflating: /content/drive/Shareddrives/CMPUT 664 : SSE/Data/sampleSubmission.csv.gz
  inflating: /content/drive/Shareddrives/CMPUT 664 : SSE/Data/testHistory.csv.gz
  inflating: /content/drive/Shareddrives/CMPUT 664 : SSE/Data/trainHistory.csv.gz
  inflating: /content/drive/Shareddrives/CMPUT 664 : SSE/Data/transactions.csv.gz

In [ ]:
# df = pd.read_csv('/content/drive/Shareddrives/CMPUT 664 : SSE/Data/customer_value/transactions.csv.gz', compression='gzip', header=0,    sep=' ', quotechar='"', error_bad_lines=False)
path = '/content/drive/Shareddrives/CMPUT 664 : SSE/Data/customer_value/transactions.csv.gz'
chunk_size=150000
batch_no=1
for chunk in pd.read_csv(path,chunksize=chunk_size,compression='gzip', error_bad_lines=False):
    df = pd.DataFrame(chunk)
    break
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,id,chain,dept,category,company,brand,date,productsize,productmeasure,purchasequantity,purchaseamount
0,86246,205,7,707,1078778070,12564,2012-03-02,12.0,OZ,1,7.59
1,86246,205,63,6319,107654575,17876,2012-03-02,64.0,OZ,1,1.59
2,86246,205,97,9753,1022027929,0,2012-03-02,1.0,CT,1,5.99
3,86246,205,25,2509,107996777,31373,2012-03-02,16.0,OZ,1,1.99
4,86246,205,55,5555,107684070,32094,2012-03-02,16.0,OZ,2,10.38
...,...,...,...,...,...,...,...,...,...,...,...
149995,22806689,18,30,3007,107766171,10562,2013-04-03,13.0,OZ,1,2.50
149996,22806689,18,57,5704,104667545,20216,2013-04-03,16.0,OZ,1,2.99
149997,22806689,18,51,5125,107265575,8089,2013-04-03,10.0,OZ,1,2.40
149998,22806689,18,19,1908,105150050,9189,2013-04-03,18.0,OZ,1,3.89
149999,22806689,18,9,907,107313070,13291,2013-04-09,24.0,OZ,1,4.99

In [ ]:
import random
purchaseAmount = list(df['productsize'].values)
mod_purchaseAmount = []
for i in range(len(purchaseAmount)):
  mod_purchaseAmount.append(purchaseAmount[i]*random.uniform(0.8, 1))

In [ ]:
df = df.drop('productsize', 1)
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.

,id,chain,dept,category,company,brand,date,productmeasure,purchasequantity,purchaseamount
0,86246,205,7,707,1078778070,12564,2012-03-02,OZ,1,7.59
1,86246,205,63,6319,107654575,17876,2012-03-02,OZ,1,1.59
2,86246,205,97,9753,1022027929,0,2012-03-02,CT,1,5.99
3,86246,205,25,2509,107996777,31373,2012-03-02,OZ,1,1.99
4,86246,205,55,5555,107684070,32094,2012-03-02,OZ,2,10.38

In [ ]:
df['productsize'] = mod_purchaseAmount
df.head()

,id,chain,dept,category,company,brand,date,productmeasure,purchasequantity,purchaseamount,productsize
0,86246,205,7,707,1078778070,12564,2012-03-02,OZ,1,7.59,10.388957
1,86246,205,63,6319,107654575,17876,2012-03-02,OZ,1,1.59,62.841769
2,86246,205,97,9753,1022027929,0,2012-03-02,CT,1,5.99,0.876179
3,86246,205,25,2509,107996777,31373,2012-03-02,OZ,1,1.99,15.929351
4,86246,205,55,5555,107684070,32094,2012-03-02,OZ,2,10.38,13.017667

In [ ]:
df.to_csv('synthetics_customer_values.csv')

In [ ]:
# cd /content/drive/Shareddrives/CMPUT 664 : SSE/Data

/content/drive/Shareddrives/CMPUT 664 : SSE/Data

In [ ]:
df = pd.read_csv('/content/breast-cancer.data',header=None)
df

FileNotFoundError: ignored